name: Build Validation

on:
    workflow_dispatch:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Use Node.js 24.17.0
              uses: actions/setup-node@v4
              with:
                  node-version: '24.17.0'

            - name: Install Dependencies
              run: npm ci

            - name: Run Checks
              run: npm run check

            - name: Run Build
              run: npm run build
